# This is a basic workflow to help you get started with Actions

name: KeepLambdaAlive

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  schedule:
    - cron: '*/5 * * * *' # Runs every day at 3pm GMT (4pm CEST)

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ping-lambda:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Ping lambda dev
        run: |
          curl --location --request POST 'https://api.dev.metakeep.xyz/v2/app/coin/balance' \
            --header 'x-api-key: {{secrets.DEV_API_KEY}}' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "coin": {
                    "currency": "0xb512854561c6081358442939c32aca47561024ab"
                },
                "of": {
                    "ethAddress": "0x09b80becbe709dd354b1363727514309d1ac3c7b"
                }
            }'
        
      - name: Ping lambda dublin
        run: curl --location --request GET 'https://api.dublin.metakeep.xyz/v2/app/list'
        
      - name: Ping lambda prod
        run: curl --location --request GET 'https://api.metakeep.xyz/v2/app/list'
